#include <stdexcept>
#include <iostream> 
using namespace std;

class MyCustomException : public exception {
public:
    MyCustomException(const char* message) : msg(message) {}

    const char* what() const throw() {
        return msg.c_str();
    }

private:
    string msg;
};

int main() {
    try {
        throw MyCustomException("Custom exception message");
    }
    catch (const MyCustomException& ex) {
        cout << "Caught custom exception: " << ex.what() << endl;
    }

    return 0;
}
